### ISSUE TITLE
Kotlin Serialization 1.3

### ISSUE THREAD

**Issue by jonasbark** [adrianbukros/github-multiplatform-example#2]
Hi Adrian,

in your blog post you wrote:
> line 18-21 Parsing the result looks more manual than what we are used to but currently this is the only solution working with Kotlin Native

Looking at https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/eap13.md#native this seems no longer the case. Or am I getting it wrong?

**Comment by adrianbukros** [comment]
You are right! I updated the repo with a new version of the serialization.
